theme: jekyll-theme-cayman
title: Ionicitude
description: AngularJS module for using the Wikitude cordova plugin in an Ionic project.
project:
  repository_url: https://github.com/Tazaf/ionicitude
  repository_name: ionicitude
documentation:
  repository_url: https://github.com/Tazaf/ionicitude/tree/gh-pages
gems:
  - jemoji
defaults:
  -
    scope:
      path: v1.0
    values:
      version: 1.0.x
